# Generated by Django 6.0.6 on 2026-06-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pythoncategories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.category'),
        ),
    ]
