# Generated by Django 6.0.6 on 2026-06-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_pythoncategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pythoncategories',
            new_name='categories',
        ),
    ]
